#define DARK_CORE_VENDOR_ID 0x1b1c

#define DARK_CORE_WIRELESS_PRODUCT_ID 0x0000
#define DARK_CORE_WIRED_PRODUCT_ID 0x000

#define DARK_CORE_SE_WIRELESS_PRODUCT_ID 0x1b51
#define DARK_CORE_SE_WIRED_PRODUCT_ID 0x1b4b

#define DARK_CORE_INTERFACE_NUM 0x1
#define DARK_CORE_ENDPOINT_ADDRESS 0x2

#define DARK_CORE_UNSPECIFIED -0x1
